version: "3"
services:
  app:
    build: .
    links:
      - mongo
    ports:
      - "7000:7000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
